// containers
#include <vector>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <array>
#include <bitset>
// general utilities
#include <utility>
#include <tuple>
#include <type_traits>
#include <typeindex>
#include <functional>
#include <memory>
#include <scoped_allocator>
#include <ratio>
#include <chrono>
#include <ctime>
#include <iterator>
// algorithms
#include <algorithm>
#include <cstdlib>
// diagnostics
#include <exception>
#include <stdexcept>
#include <cassert>
#include <cerrno>
#include <system_error>
// strings and characters
#include <string>
#include <cctype>
#include <cwctype>
#include <cstring>
#include <cwchar>
#include <cstdlib> // 和上面重复了
#include <cuchar>
#include <regex>
// input/output
#include <iosfwd>
#include <iostream>
#include <ios>
#include <streambuf>
#include <istream>
#include <ostream>
#include <iomanip>
#include <sstream>
#include <cctype>
#include <fstream>
#include <cstdio>
#include <cwchar>
// localization
#include <locale>
#include <clocale>
#include <codecvt>
// language support
#include <limits>
#include <climits>
#include <cfloat>
#include <cstdint>
#include <new>
#include <typeinfo>
#include <exception>
#include <initializer_list>
#include <cstddef>
#include <cstdarg>
#include <csetjmp>
#include <cstdlib>
#include <ctime>
#include <csignal>
// numerics
#include <complex>
#include <valarray>
#include <numeric>
#include <cmath>
#include <cstdlib>
#include <random>
// concurrency
#include <atomic>
#include <condition_variable>
#include <future>
#include <mutex>
#include <thread>
// c compatibility
#include <cinttypes>
#include <cstdbool>
#include <ccomplex>
#include <cfenv>
#include <cstdalign>
#include <ctgmath>